[build]
builder = "nixpacks"

[deploy]
startCommand = "python simple_backend.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
restartPolicyDelay = 30

[env]
PORT = "8000"
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"

